# Generated by Django 4.2.3 on 2026-03-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name for this ad unit (e.g., 'Home Page Popunder')", max_length=200)),
                ('ad_type', models.CharField(choices=[('popunder', 'Popunder'), ('social_bar', 'Social Bar'), ('banner', 'Display Banner'), ('native', 'Native Banner'), ('smartlink', 'Smartlink')], help_text='Type of Adsterra ad unit', max_length=20)),
                ('position', models.CharField(choices=[('head', 'Head Section (for Popunder)'), ('body_top', 'Body Top (after opening <body>)'), ('body_bottom', 'Body Bottom (before closing </body>)'), ('sidebar', 'Sidebar'), ('content_top', 'Before Content'), ('content_bottom', 'After Content'), ('between_content', 'Between Content Items'), ('player_top', 'Above Video Player'), ('player_bottom', 'Below Video Player')], help_text='Where to display this ad on the page', max_length=30)),
                ('code', models.TextField(help_text='Paste your Adsterra code exactly as provided (including <script> tags)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to disable this ad without deleting it')),
                ('show_on_mobile', models.BooleanField(default=True, help_text='Show this ad on mobile devices')),
                ('show_on_desktop', models.BooleanField(default=True, help_text='Show this ad on desktop devices')),
                ('show_on_pages', models.CharField(blank=True, help_text='Comma separated page types: home,anime,movie,series,player (leave empty for all pages)', max_length=200)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority. Use for A/B testing or rotation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Unit',
                'verbose_name_plural': 'Ad Units',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
